### ISSUE TITLE
Unable to run vmnet example

### ISSUE THREAD

**Issue by Mat001** [Lamden/vmnet#7]
@wywfalcon 
Tried to run the example as in README :
`$ cd examples/sample`
`$ python3 test_sample.py`

Docker starts containers but then it hits error
> ERROR: pull access denied for vmnet_base.dev, repository does not exist or may require 'docker login'

I have docker-compose running and I'm logged in to docker-hub.
Am I missing something trivial? (I'm running Ubuntu 18.04)

Full log is this:
`python test_sample.py `
> 2018-07-05 12:55:12.287 vmnet.test.base[12234][MainProcess] INFO Starting docker...
2018-07-05 12:55:12.785 vmnet[12331][MainProcess] INFO Building vmnet_base.dev...
unable to prepare context: the Dockerfile (/home/m/repositories/vmnet/examples/sample/docker_dir/vmnet_base.dev) must be within the build context
2018-07-05 12:55:12.799 vmnet[12331][MainProcess] INFO Done.
2018-07-05 12:55:12.918 vmnet.test.base[12234][MainProcess] INFO Running test "log_test" and waiting for 5s...
2018-07-05 12:55:13.000 vmnet[12414][MainProcess] INFO Building vmnet_base.dev...
unable to prepare context: the Dockerfile (/home/m/repositories/vmnet/examples/sample/docker_dir/vmnet_base.dev) must be within the build context
2018-07-05 12:55:13.011 vmnet[12414][MainProcess] INFO Done.
Creating network "vmnet_vmnet" with driver "bridge"
Pulling vmnet_node_2 (vmnet_base.dev:latest)...
ERROR: pull access denied for vmnet_base.dev, repository does not exist or may require 'docker login'
Error: No such container: vmnet_node_2
Error: No such container: vmnet_node_1
Error: No such container: vmnet_node_3
2018-07-05 12:55:17.974 vmnet.test.base[12234][MainProcess] DEBUG Press enter to exit...
Error: No such container: vmnet_node_4
Error: No such container: vmnet_node_5

**Comment by Mat001** [comment]
@wywfalcon 
I could run the thing is I build image manually.
I went into sample/scripts dir and ran `docker build . -f ../docker_dir/vmnet_base.dev`

If I don't build it manually and just run `python3 test_sample.py` then I get pull access denied/docker login error.

Do you guys use private image from docker-hub that outer folks don't have access to?
I'll write a PR to build the image manually in order for README example to work?

**Comment by wywfalcon** [comment]
New docs and many new features will be ready after Anarchy Net for Cilantro is out. Thanks for your patience.
